html update
code-differently/code-differently-24-q1 pull request #10
Opened 2024-02-27 15:19 UTC by 00USER1X

2024-02-27 16:05 UTC, anthonydmays requested changes

2024-02-27 16:05 UTC, anthonydmays commented on lesson_01/Mekhi html/mekhi.html
There are significant differences between your HTML version and your MARKDOWN version. Continue to iterate on this until they are nearly identical. Good progress though!

2024-02-29 16:17 UTC, HeirJordan3 requested changes

2024-02-29 16:17 UTC, HeirJordan3 commented on MekhiReadMe/readMe.md
Still see some significant differences from the ReadMe file to the HTML file.

2024-02-29 16:53 UTC, 00USER1X reviewed
fixed differences

2024-03-01 02:49 UTC, anthonydmays approved these changes
Images are still incorrect.

2024-03-01 02:50 UTC, anthonydmays approved these changes

2024-03-01 02:51 UTC, merged