recent pr
code-differently/code-differently-24-q1 pull request #108
Opened 2024-03-05 14:54 UTC by 00USER1X

2024-03-05 17:26 UTC, anthonydmays requested changes

2024-03-05 17:26 UTC, anthonydmays commented on lesson_02/quiz/.settings/org.eclipse.buildship.core.prefs
There are still a bunch of extra changes here that you need to remove. Please revert anything that is not `MekhiQuiz.java` or `application.yml`.

2024-03-06 18:08 UTC, 00USER1X reviewed
Ive reverted all unnecessary files.

2024-03-06 18:57 UTC, anthonydmays requested changes

2024-03-06 18:57 UTC, anthonydmays commented on lesson_02/quiz/.settings/org.eclipse.buildship.core.prefs
You still haven't reverted the changes. You will probably need to use the `git checkout` command to get the state of the files before you changed them and then `git commit` to put them back to that state. Alternatively, you can update your `main` branch and then make a new, clean branch that you can use to re-apply your changes to `Lesson3.java` and submit a new PR. That might be the better option, but it's up to you.

2024-03-07 15:53 UTC, closed without merging