Lesson3
code-differently/code-differently-24-q1 pull request #110
Opened 2024-03-05 15:12 UTC by SherllinT

2024-03-05 15:15 UTC, anthonydmays requested changes

2024-03-05 15:15 UTC, anthonydmays commented on lesson_03/quiz/lesson_03_quiz/src/main/java/com/codedifferently/lesson3/quizzes/SherllinTQuiz.java
> +            AnswerChoice.C, "null",
Don't need C and D choices, you can just remove those and it should still work.

2024-03-05 15:15 UTC, anthonydmays commented on lesson_03/quiz/lesson_03_quiz/src/main/java/com/codedifferently/lesson3/quizzes/SherllinTQuiz.java
> +public class SherllinTQuiz implements QuizQuestionProvider {
Great questions!

2024-03-05 15:15 UTC, anthonydmays commented on lesson_02/quiz/lesson_02_quiz/src/main/java/com/codedifferently/lesson2/Lesson2.java
Please delete or revert this file since you're not submitting this.

2024-03-05 15:32 UTC, SherllinT commented on lesson_03/quiz/lesson_03_quiz/src/main/java/com/codedifferently/lesson3/quizzes/SherllinTQuiz.java
> +public class SherllinTQuiz implements QuizQuestionProvider {
thank you!!

2024-03-06 18:59 UTC, anthonydmays requested changes

2024-03-06 18:59 UTC, anthonydmays commented on lesson_02/quiz/lesson_02_quiz/src/main/java/com/codedifferently/lesson2/Lesson2.java
I still see `Lesson2.java` in this pull request. You should probably use the `git checkout` command to undo changes, use `git commit` to save to the repository, then `git push` to GitHub so that the pull request will get updated.

2024-03-06 21:30 UTC, closed without merging