adding the ReadMe Markdown File
code-differently/code-differently-24-q1 pull request #14
Opened 2024-02-27 15:49 UTC by javyW

Javyen Ware's Copy of the ReadMe Markdown file

2024-02-27 16:07 UTC, anthonydmays requested changes
Would like you to include something that speaks to how co-workers can best engage with you. Please update to include these details. Otherwise, well done!

2024-02-27 18:46 UTC, javyW reviewed
I changed a part of my markdown file to include how best co-workers can engage with you.

2024-02-27 23:37 UTC, anthonydmays requested changes

2024-02-27 23:37 UTC, anthonydmays commented on lesson_00/JavyenWare/RM.markdown
This file should be named README.md, I missed this on the original review.

2024-02-28 13:15 UTC, javyW commented on lesson_00/JavyenWare/RM.markdown
> +<img src="img/CoolTerrariaPics.jpeg" alt="Cool Terraria Pics" width="200" height="200">
I Fixed the image. How I fixed it was that you have to copy and paste the image url from the original image into the src tag.

2024-02-28 17:28 UTC, anthonydmays approved these changes
LGTM

2024-02-28 17:29 UTC, merged