Jordan branch
code-differently/code-differently-24-q1 pull request #18
Opened 2024-02-27 16:42 UTC by HeirJordan3

Added the HTML version of my README.

2024-02-27 18:38 UTC, anthonydmays requested changes

2024-02-27 18:38 UTC, anthonydmays commented on lesson_01/Jordan/ReadMe.html
There are some significant differences between the visual appearance of this file and the markdown version. Please fix.

2024-02-27 18:39 UTC, anthonydmays commented on lesson_01/Jordan/ReadMe.html
Notably, the kobe picture is missing and the section about family and pets. There are other things too, so keep working on it.

2024-02-28 16:49 UTC, HeirJordan3 commented on lesson_01/Jordan/ReadMe.html
Made the changes required should be good to go!

2024-02-28 17:26 UTC, anthonydmays requested changes
Still noting some significant differences, but closer. Please adjust.

2024-02-28 17:26 UTC, anthonydmays commented on lesson_01/Jordan/ReadMe.html
> +    <h3>🍳 Chef Jordan in the House</h3>
Not matching the consistency of the style in your markdown version

2024-02-28 17:26 UTC, anthonydmays commented on lesson_01/Jordan/ReadMe.html
> +    <p><img src="https://github.com/HeirJordan3/CodeDifferently_README/blob/main/assets/Kobe.JPG?raw=true" alt="" width=30%></p>
This appears differently sized in your markdown version.

2024-02-28 17:26 UTC, anthonydmays commented on lesson_01/Jordan/ReadMe.html
> +    <h2>🎯 Goals for the Coming Year</h2>
Missing some content in this section.

2024-02-28 22:04 UTC, HeirJordan3 reviewed
made some changes

2024-02-29 02:32 UTC, anthonydmays approved these changes

2024-02-29 02:32 UTC, merged