Added README.md under lesson_00
code-differently/code-differently-24-q1 pull request #2
Opened 2024-02-26 18:27 UTC by cibezim

I have added my README.md to my new folder chukwumaibezim under lesson_00 from my branch cibezm. I do not want my README published publicly.

2024-02-26 21:09 UTC, anthonydmays requested changes
Please fix your html changes or remove and add via a separate PR since only the markdown version is due initially. Up to you whichever you choose.

2024-02-26 21:33 UTC, cibezim commented on lesson_00/chukwumaibezim/README.html
> +<!DOCTYPE html>
deleted html file

2024-02-27 20:03 UTC, cibezim reviewed
all done

2024-02-27 21:25 UTC, anthonydmays requested changes

2024-02-27 21:25 UTC, anthonydmays commented on lesson_00/chukwumaibezim/README.md
Almost there! Please add something that will help your professional colleagues understand how to best work with you. Be happy to approve once you've added that.

2024-02-27 21:44 UTC, anthonydmays approved these changes
LGTM

2024-02-27 21:44 UTC, cibezim commented on lesson_00/chukwumaibezim/README.md
Updated with information

2024-02-27 21:44 UTC, merged