Html
code-differently/code-differently-24-q1 pull request #20
Opened 2024-02-27 17:36 UTC by Aaron2278

Html markup page based off of my previous readME markdown.

2024-02-27 18:41 UTC, anthonydmays requested changes

2024-02-27 18:41 UTC, anthonydmays commented on lesson_00/aaronsantiago/README.md
This looks broken, please fix.

2024-02-27 18:41 UTC, anthonydmays commented on lesson_01/AaronSantiago/Aaron.html
There are some significant visual differences between your HTML version and your MARKDOWN version. The markdown version is borked for me, so I can't provide more detail than that ATM.

2024-02-27 19:46 UTC, Aaron2278 reviewed
fixed the problem with the readME file and fixed something on the html file.

2024-02-27 21:35 UTC, anthonydmays requested changes

2024-02-27 21:35 UTC, anthonydmays commented on lesson_01/AaronSantiago/Aaron.html
> +  <h1 class="animate__animated animate__fadeIn">Personal README - Aaron Santiago</h1>
There are a couple of diffs I'd like you to resolve. Please update the font and the title of this page (your name is in square brackets in the markdown version, for instance).

2024-02-27 21:35 UTC, anthonydmays commented on lesson_01/AaronSantiago/Aaron.html
> +  <img class="animate__animated animate__fadeIn" src="https://remote-tools-images.s3.amazonaws.com/programmer-memes/11.jpg" alt="Programmer Meme">
This image is smaller than in the markdown version. Please adjust.

2024-02-28 17:22 UTC, anthonydmays requested changes

2024-02-28 17:22 UTC, anthonydmays commented on .vscode/settings.json
Please revert this change. You can use this article for help: https://www.freecodecamp.org/news/git-revert-file-reverting-a-file-to-a-previous-commit/

2024-02-28 17:22 UTC, anthonydmays commented on lesson_01/AaronSantiago/Aaron.html
> +  <img class="animate__animated animate__fadeIn" src="https://remote-tools-images.s3.amazonaws.com/programmer-memes/11.jpg" alt="Programmer Meme">
Still not quite there.

2024-02-28 20:50 UTC, Aaron2278 commented
vscode folder, setting.json statement dupe should be resolved now.

2024-02-29 02:27 UTC, anthonydmays requested changes

2024-02-29 02:27 UTC, anthonydmays commented on .vscode/settings.json
Still not addressed.

2024-02-29 02:27 UTC, anthonydmays commented on lesson_01/README.md
Please revert this change.

2024-02-29 02:27 UTC, anthonydmays commented on lesson_01/AaronSantiago/Aaron.html
> +  <img class="animate__animated animate__fadeIn" src="https://remote-tools-images.s3.amazonaws.com/programmer-memes/11.jpg" alt="Programmer Meme">
Still not matching.

2024-02-29 02:27 UTC, anthonydmays commented on lesson_01/AaronSantiago/Aaron.html
This is unresolved, please continue making adjustments.

2024-03-01 02:48 UTC, merged