Randy README.md
code-differently/code-differently-24-q1 pull request #28
Opened 2024-02-27 20:15 UTC by RandyCastr0

[Randy README 2.md](https://github.com/code-differently/code-differently-24-q1/files/14425190/Randy.README.2.md)

2024-02-27 20:16 UTC, RandyCastr0 commented
fixed broken image

2024-02-27 20:44 UTC, anthonydmays requested changes

2024-02-27 20:44 UTC, anthonydmays commented on lesson_00/RandyCastro/Randy Readme.md
> +![Image Description](https://github.com/RandyCastr0/pics/raw/main/IMG_0786.jpg)
This image is brokken. You should probably use a repo relative link here.

2024-02-27 21:30 UTC, RandyCastr0 commented
[Randy README 3.md](https://github.com/code-differently/code-differently-24-q1/files/14425987/Randy.README.3.md)

2024-02-27 21:42 UTC, anthonydmays requested changes

2024-02-27 21:42 UTC, anthonydmays commented on lesson_00/RandyCastro/Randy Readme.md
The name of this file should be README.md. Please rename

2024-02-27 21:47 UTC, RandyCastr0 commented
[ README .md](https://github.com/code-differently/code-differently-24-q1/files/14426084/README.md)

2024-02-28 03:16 UTC, anthonydmays approved these changes
LGTM

2024-02-28 03:17 UTC, RandyCastr0 reviewed
Changed file name and update code

2024-02-28 03:17 UTC, merged