Sherllin t patch 1
code-differently/code-differently-24-q1 pull request #29
Opened 2024-02-27 21:37 UTC by SherllinT

2024-02-27 21:52 UTC, anthonydmays requested changes

2024-02-27 21:52 UTC, anthonydmays commented on lesson_01/ReadMe.html
This file is in the wrong location. Please move to a sub-folder with your name. Happy to approve once moved.

2024-02-28 01:39 UTC, anthonydmays commented
I see that you have PR #33 with the same README. You can close this PR and use that one for your work.

2024-02-29 15:50 UTC, SherllinT commented on lesson_01/ReadMe.html
Noted, I have resolved and re-submitted in correct folder!

2024-02-29 16:22 UTC, anthonydmays requested changes

2024-02-29 16:22 UTC, anthonydmays commented on lesson_01/Sherllin/Readme.HTML
Your version is missing the bottom borders for the title. Please fix.

2024-02-29 21:46 UTC, anthonydmays approved these changes

2024-02-29 21:50 UTC, merged