Feat: added files for Librarian checking out books,
code-differently/code-differently-24-q1 pull request #296
Opened 2024-03-25 16:11 UTC by kjknows

-implemented methods
-address complicated errors
-corrected constructors

2024-03-25 21:36 UTC, anthonydmays requested changes

2024-03-25 21:36 UTC, anthonydmays commented on lesson_10/solid/solid_app/src/main/java/com/codedifferently/lesson10/library/Library.java
I think it would be best if you focused on implementing the `Librarian` requirement first, then attempt to support different types of media.

2024-03-26 13:10 UTC, kjknows commented on lesson_10/solid/solid_app/src/main/java/com/codedifferently/lesson10/library/Library.java
So originally I did that and was hype then I got confused when i started making my other files and started making unnecessary changes, and got confused.

2024-03-26 14:02 UTC, closed without merging

2024-03-26 15:43 UTC, anthonydmays commented on lesson_10/solid/solid_app/src/main/java/com/codedifferently/lesson10/library/Library.java
Why close the PR? Are you sending a new one instead?