Kyvon Thompsons Read ME
code-differently/code-differently-24-q1 pull request #3
Opened 2024-02-26 20:45 UTC by KRose77

2024-02-26 21:03 UTC, anthonydmays commented on lesson_00/Kyvonreadme.md
You've put the file in the wrong place. Your README.md file should be located in the /lesson_00/kyvon/ directory.

2024-02-26 21:04 UTC, anthonydmays commented on lesson_00/Kyvonreadme.md
> +[![](https://markdown-videos-api.jorgenkh.no/youtube/814SngdguwQ)](https://youtu.be/814SngdguwQ)
Link is broken when I view it.

2024-02-26 21:05 UTC, anthonydmays commented on lesson_00/Kyvonreadme.md
> +You can reach me primarily by email or linkedin and you can see more of my work on instagram @rosevisualsss
nit: Should be spelled "LinkedIn", not "linkedin". Fix the casing of instagram as well and other proper nouns.

2024-02-26 21:07 UTC, anthonydmays requested changes
Thanks for sending! Please see comments and make changes.

2024-02-26 21:07 UTC, anthonydmays commented on lesson_00/Kyvonreadme.md
> +# Learn about Kyvon Thompson
This is a decent start, but you should add something about yourself that will help other collaborate with you professionally (e.g. what are your best working hours? how do you prefer that teammates communicate with you?).

2024-02-27 16:24 UTC, KRose77 reviewed
Fixed casing.

2024-02-27 18:26 UTC, anthonydmays requested changes

2024-02-27 18:26 UTC, anthonydmays commented on lesson_00/Kyvon/Kyvonreadme.md
The name of the file is incorrect (should be README.md).

2024-02-27 18:26 UTC, anthonydmays commented on lesson_00/Kyvon/Kyvonreadme.md
> +You can reach me primarily by email or LinkedIn @KyvonThompson and Rosevisualsss52@gmail.com and you can see more of my work on Instagram @rosevisualsss
More than welcome to use your real email address here, but use caution. Just making sure to mention that here.

2024-02-27 18:49 UTC, anthonydmays approved these changes
LGTM

2024-02-27 18:49 UTC, merged