README.html
code-differently/code-differently-24-q1 pull request #31
Opened 2024-02-27 21:54 UTC by cibezim

Adding README.html to lesson_01

2024-02-27 22:14 UTC, anthonydmays requested changes

2024-02-27 22:14 UTC, anthonydmays commented on lesson_01/chukwumaibezim/README.html
Still some tweaks you need to make. Please left align the content as you have it in your markdown file. Also, there are line separators in the markdown that aren't present in your HTML.

2024-02-28 19:00 UTC, anthonydmays requested changes

2024-02-28 19:00 UTC, anthonydmays commented on lesson_01/chukwumaibezim/README.html
Images are still centered when they should be left aligned.

2024-02-28 19:40 UTC, cibezim reviewed
fixed

2024-02-29 15:23 UTC, closed without merging