Feat: Added SQL code, Model, and REPO
code-differently/code-differently-24-q1 pull request #337
Opened 2024-04-01 15:00 UTC by Moibrahi7

2024-04-01 15:40 UTC, anthonydmays requested changes
Please integrate with the `LibraryDbDataLoader` and add a test.

2024-04-01 15:50 UTC, anthonydmays commented
> Please integrate with the `LibraryDbDataLoader` and add a test.

I just realized I forgot to call out adding a test for this in the assignment details. I won't dock credit if you don't do it, but you still should.

2024-04-01 15:59 UTC, Moibrahi7 commented
Is user suppose to go under patron

2024-04-02 00:28 UTC, anthonydmays requested changes

2024-04-02 00:28 UTC, anthonydmays commented on lesson_14/db/db_app/src/main/java/com/codedifferently/lesson14/models/LibraryUserModel.java
> +@Table(name = "guests")
Should be `@Table(name = "library_users")`.

2024-04-02 00:28 UTC, closed without merging