KenrickHTML
code-differently/code-differently-24-q1 pull request #36
Opened 2024-02-28 20:28 UTC by Kenrixkk22

adds HTML and Style sheet

2024-02-28 21:30 UTC, anthonydmays requested changes
Some significant differences between the html and markdown version. Continue making adjustments.

2024-02-28 21:30 UTC, anthonydmays commented on lesson_00/kenricksutherland/README.md
Why did you make a completely new README? Delete this and I'll use your original README to judge your HTML version.

2024-02-28 21:30 UTC, anthonydmays commented on lesson_01/Kenrick/index.html
> +  <li>Chicken and Broccoli Alfredo</li>
The space between the bullets and text is longer than it should be, please fix.

2024-02-28 21:30 UTC, anthonydmays commented on lesson_01/Kenrick/index.html
> +  <li>Chicken and Broccoli Alfredo</li>
Also, the alignment is weird. Should be flush left.

2024-02-29 02:46 UTC, anthonydmays requested changes
Almost there! Keep it going.

2024-02-29 02:46 UTC, anthonydmays commented on lesson_01/Kenrick/index.html
> +<h3>Favorite FOODS 🍕</h3>
Bulleted list missing bullets

2024-02-29 02:46 UTC, anthonydmays commented on lesson_01/Kenrick/index.html
> +<h3>Favorite Quotes</h3>
Bulleted list missing bullets.

2024-02-29 18:56 UTC, HeirJordan3 requested changes

2024-03-01 02:39 UTC, anthonydmays approved these changes
Missing airliner picture and list bullets.

2024-03-01 02:40 UTC, merged