Randy's HTML
code-differently/code-differently-24-q1 pull request #38
Opened 2024-02-29 02:33 UTC by RandyCastr0

2024-02-29 02:51 UTC, anthonydmays requested changes

2024-02-29 02:51 UTC, anthonydmays commented on lesson_01/RandyCastro/index.html
> +<ol>
List indent is too far from the left margin, please adjust. Same for the list below.

2024-02-29 02:51 UTC, anthonydmays commented on lesson_01/RandyCastro/index.html
> +
There are duplicated tags. There should only be one of each of the following tags: <html/>, <head/>, <body/>, and <title/>. Please adjust.

2024-02-29 15:31 UTC, HeirJordan3 requested changes

2024-02-29 15:31 UTC, HeirJordan3 commented on lesson_01/RandyCastro/index.html
Missing border under the titles.

2024-03-01 02:33 UTC, anthonydmays approved these changes
LGTM

2024-03-01 02:34 UTC, merged