feat: adds quiz questions chore: adds answers to yml
code-differently/code-differently-24-q1 pull request #95
Opened 2024-03-04 19:17 UTC by RichHawkins

2024-03-04 20:09 UTC, anthonydmays requested changes

2024-03-04 20:09 UTC, anthonydmays commented on lesson_03/quiz/lesson_03_quiz/src/test/resources/application.yml
> +     - $2y$10$OaEPPpERWwAkNghJg6tzBuopXjTwDhu3knf.DNYAJ2OjaRsKfBU/2
You should only have two answers specified since you have two questions.

2024-03-04 21:32 UTC, anthonydmays requested changes

2024-03-04 21:32 UTC, anthonydmays commented on lesson_03/quiz/lesson_03_quiz/src/main/java/com/codedifferently/lesson3/quizzes/RichHawkinsQuiz.java
Need to fix formatting on this file.

2024-03-04 22:44 UTC, RichHawkins commented on lesson_03/quiz/lesson_03_quiz/src/main/java/com/codedifferently/lesson3/quizzes/RichHawkinsQuiz.java
ran spotlessApply again, format should now be correct.

2024-03-04 22:47 UTC, anthonydmays commented on lesson_03/quiz/lesson_03_quiz/src/main/java/com/codedifferently/lesson3/quizzes/AnthonyMaysQuiz.java
Please revert changes to this file.

2024-03-05 01:18 UTC, RichHawkins commented on lesson_03/quiz/lesson_03_quiz/src/main/java/com/codedifferently/lesson3/quizzes/AnthonyMaysQuiz.java
reverted file to original

2024-03-05 01:27 UTC, anthonydmays approved these changes
LGTM

2024-03-05 01:28 UTC, merged